name: Deltares_GPP_cmd
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2021.5.30=py36ha15d459_0
  - intel-openmp=2022.0.0=haa95532_3663
  - jpeg=9e=h8ffe710_2
  - krb5=1.19.3=hc8ab02b_0
  - libcurl=7.83.1=h789b8ee_0
  - libssh2=1.10.0=h9a1e1f7_3
  - libtiff=4.2.0=h0c97f57_3
  - libzlib=1.2.12=h8ffe710_2
  - lz4-c=1.9.3=h8ffe710_1
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36h196d8e1_0
  - mkl_fft=1.3.0=py36h46781fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - numpy=1.19.2=py36hadc3359_0
  - numpy-base=1.19.2=py36ha3acd2a_0
  - openssl=3.0.5=h8ffe710_1
  - pandas=1.1.5=py36hd77b12b_0
  - pip=21.2.2=py36haa95532_0
  - proj=8.0.0=h1cfcee9_0
  - pyproj=3.0.1=py36h86093ec_1
  - python=3.6.13=h3758d61_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.6=2_cp36m
  - pytz=2021.3=pyhd3eb1b0_0
  - setuptools=58.0.4=py36haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py36h7fe50ca_0
  - xz=5.2.6=h8d14728_0
  - zlib=1.2.12=h8ffe710_2
  - zstd=1.5.2=h6255e5f_4
  - pip:
    - altair==4.1.0
    - attrs==22.2.0
    - backcall==0.2.0
    - branca==0.5.0
    - cachetools==4.2.4
    - cftime==1.6.0
    - charset-normalizer==2.0.12
    - colorama==0.4.5
    - cycler==0.11.0
    - decorator==5.1.1
    - earthengine-api==0.1.335
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - folium==0.13.0
    - future==0.18.2
    - google-api-core==2.8.2
    - google-api-python-client==2.52.0
    - google-auth==2.15.0
    - google-auth-httplib2==0.1.0
    - google-cloud-core==2.3.1
    - google-cloud-storage==2.0.0
    - google-crc32c==1.3.0
    - google-resumable-media==2.3.3
    - googleapis-common-protos==1.56.3
    - hesseflux==4.5
    - httplib2==0.21.0
    - idna==3.4
    - importlib-metadata==4.8.3
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==3.0.3
    - joblib==1.1.1
    - jsonschema==3.2.0
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - netcdf4==1.5.6
    - openpyxl==3.0.10
    - parso==0.7.1
    - patsy==0.5.3
    - pickleshare==0.7.5
    - pillow==8.4.0
    - prompt-toolkit==3.0.36
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.14.0
    - pyjams==1.27
    - pyparsing==3.0.9
    - pyrsistent==0.18.0
    - requests==2.27.1
    - rsa==4.9
    - schwimmbad==0.3.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - scikit-learn
    - statsmodels==0.12.2
    - threadpoolctl==3.1.0
    - toolz==0.12.0
    - traitlets==4.3.3
    - typing-extensions==4.1.1
    - uritemplate==4.1.1
    - urllib3==1.26.13
    - wcwidth==0.2.5
    - xlrd==2.0.1
    - zipp==3.6.0
